"use strict";
// Hello my name is Shayan, I have no projects or programms in TS but alot in JS, I had made a tic tac toe, stop watch, 2d shooting game using canvas, quiz application from scratch and some other projects with the help of ytb for practice, includes pong game and much monitorEventLoopDelay...
